--- #YAML:1.0
name:                HTML-Template-Pro-Extension
version:             0.10
abstract:            Plugin extension for HTML::Template::Pro module
license:             ~
author:              
    - Emiliano Bruni <info@ebruni.it>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTML::Parser:                  0
    HTML::Template::Pro:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
